name: "Remotely"
description: "Remotely server"
url: https://github.com/lordrak007/haas-addon-repo/remotely
webui: "[PROTO:ssl]://[HOST]:[PORT:5000]"
panel_icon: mdi:remotedesktop
version: "0.1.8"
slug: "remotely"
init: false
arch:
  - amd64
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web interface
host_network: true
map:
  - addon_config:rw

