name: "eLAN MQTT NET"
description: "MQTT gateway for eLan using .Net"
url: https://github.com/lordrak007/haas-addon-repo
version: "V1.0.1"
slug: "elan2mqttnet"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
auth_api: true

services:
  - mqtt:need

options:
  "eLan URL": "http://ip.address"
  "eLan username": "user"
  "eLan password": "password"
  log_level: "info"
  autodiscovery_enabled: "true"

schema:
  "eLan URL": "str"
  "eLan username": "str"
  "eLan password": "str"
  log_level: "match(^(trace|debug|info|notice|warning|error|fatal)$)"
  autodiscovery_enabled: "bool?"
